CREATE VIEW [dbo].[vw_aircraft_details] AS 
SELECT 
	_air.TAIL_NUMBER
	, _mdl.MODEL_NUMBER
	, _mdl.DESCRIPTION AS MODEL_DESCRIPTION 
	, _cmp.COMPANY_NAME AS OWNER_COMPANY_NAME
	, _coc.CODE AS COMPANY_COUNTRY_CODE
	, _coc.COUNTRY_NAME AS COMPANY_COUNTRY_NAME
	, _coc.SDF_COC_002 AS CONTINENT
	, _coc.SDF_COC_003 AS BELONGS_TO_EU
FROM [dbo].AIRCRAFT AS _air
JOIN [dbo].MODEL AS _mdl ON _mdl.MDL_AUTO_KEY = _air.MDL_AUTO_KEY
JOIN [dbo].COMPANIES AS _cmp ON _cmp.CMP_AUTO_KEY = _air.CMP_OWNER
JOIN [dbo].COUNTRY_CODES AS _coc ON _coc.COC_AUTO_KEY = _cmp.COC_AUTO_KEY
