CREATE TABLE [dbo].[AIRCRAFT]
(
	[ACT_AUTO_KEY] INT NOT NULL PRIMARY KEY, 
    [MDL_AUTO_KEY] INT NOT NULL, 
    [CMP_OWNER] INT NOT NULL, 
    [TAIL_NUMBER] VARCHAR(50) NOT NULL, 
    CONSTRAINT [FK_AIRCRAFT_MODEL] FOREIGN KEY ([MDL_AUTO_KEY]) REFERENCES [dbo].[MODEL](MDL_AUTO_KEY), 
    CONSTRAINT [FK_AIRCRAFT_COMPANIES] FOREIGN KEY ([CMP_OWNER]) REFERENCES [dbo].[COMPANIES]([CMP_AUTO_KEY])    
)
